Repository DobDub/TrackMyDegree, pull requests merged in 2025-01, with the labels that each got.

#46 Bug: Fixed cors options
  Back-End/index.ts
Labels: bug

#47 Refactor/testing container run
  Back-End/ping-backend.sh
  docker-compose.yml
  entrypoint-sql.sh
Labels: bug

#53 Bug/broken auth
  Back-End/controllers/appUserController/appUserController.ts
  Back-End/controllers/appUserController/appUser_types.d.ts
  Back-End/controllers/authController/authController.ts
  Back-End/controllers/degreeController/degreeController.ts
  Back-End/routes/appUser.ts
  init.sql
Labels: bug

#55 Added correct url for docker
  Back-End/tests/courses.test.js
  Back-End/tests/login.test.js
  Back-End/tests/signup.test.js
  Back-End/tests/test-db.test.js
  docker-compose.yml
Labels: bug

#69 Added Scrapers and course data
  Scraping/Scrapers/AERO_scraper.py
  Scraping/Scrapers/BCEE_scraper.py
  Scraping/Scrapers/BLDG_scraper.py
  Scraping/Scrapers/CIVI_scraper.py
  Scraping/Scrapers/COEN_scraper.py
  Scraping/Scrapers/COMP_scraper.py
  Scraping/Scrapers/ELEC_scraper.py
  Scraping/Scrapers/INDU_scraper.py
  Scraping/Scrapers/MECH_scraper.py
  Scraping/Scrapers/MIAE_scraper.py
  Scraping/course-lists/AERO_courses.json
  Scraping/course-lists/BCEE_courses.json
  Scraping/course-lists/BLDG_courses.json
  Scraping/course-lists/CIVI_courses.json
  Scraping/course-lists/COEN_courses.json
  Scraping/course-lists/COMP_courses.json
  Scraping/course-lists/ELEC_courses.json
  Scraping/course-lists/INDU_courses.json
  Scraping/course-lists/MECH_courses.json
  Scraping/course-lists/MIAE_courses.json
  course data/COMP_SOEN_courses.json
  course data/COMP_SOEN_scraped_page.html
  course data/ENCS_courses.json
  course data/ENCS_scraped_page.html
  course data/ENGR_courses.json
  course data/ENGR_scraped_page.html
  course data/Parser.py
  course data/Scraper.py
  course data/Scraping/Scrapers/AERO_scraper.py
  course data/Scraping/Scrapers/BCEE_scraper.py
  course data/Scraping/Scrapers/BLDG_scraper.py
  course data/Scraping/Scrapers/CIVI_scraper.py
  course data/Scraping/Scrapers/COEN_scraper.py
  course data/Scraping/Scrapers/COMP_scraper.py
  course data/Scraping/Scrapers/ELEC_scraper.py
  course data/Scraping/Scrapers/INDU_scraper.py
  course data/Scraping/Scrapers/MECH_scraper.py
  course data/Scraping/Scrapers/MIAE_scraper.py
  course data/Scraping/course-lists/AERO_courses.json
  course data/Scraping/course-lists/BCEE_courses.json
  course data/Scraping/course-lists/BLDG_courses.json
  course data/Scraping/course-lists/CIVI_courses.json
  course data/Scraping/course-lists/COEN_courses.json
  course data/Scraping/course-lists/COMP_courses.json
  course data/Scraping/course-lists/ELEC_courses.json
  course data/Scraping/course-lists/INDU_courses.json
  course data/Scraping/course-lists/MECH_courses.json
  course data/Scraping/course-lists/MIAE_courses.json
  course data/engineering_core.json
  course data/general_education_electives/humanities.json
  course data/general_education_electives/other_complementary_studies.json
  course data/general_education_electives/social_sciences.json
  course data/soen_courses.js
  course data/soen_courses/computer_science_group.json
  course data/soen_courses/engineering_natural_science_group.json
  course data/soen_courses/soen_core.json
  course data/soen_courses/soen_electives.json
Labels: Data

#67 Feat/api user data
  Back-End/controllers/userDataController/userDataController.ts
  Back-End/controllers/userDataController/user_data_types.ts
  Back-End/index.ts
  Back-End/routes/userData.ts
  Back-End/tests/login.test.js
  Back-End/tests/userData.test.js
  front-end/.dockerignore
Labels: enhancement
