Repository DobDub/TrackMyDegree, pull requests merged in 2025-03, with the labels that each got.

#155 Fixed Sentry Bug & Added Fall/Winter Semester
  .gitignore
  Back-End/.env
  Back-End/controllers/CourseXCPController/CourseXCPController.ts
  Back-End/controllers/DBController/DBController.ts
  Back-End/controllers/DegreeXCPController/DegreeXCPController.ts
  Back-End/controllers/adminController/adminController.ts
  Back-End/controllers/appUserController/appUserController.ts
  Back-End/controllers/authController/authController.ts
  Back-End/controllers/courseController/coursesController.ts
  Back-End/controllers/coursepoolController/coursepoolController.ts
  Back-End/controllers/deficiencyController/deficiencyController.ts
  Back-End/controllers/degreeController/degreeController.ts
  Back-End/controllers/exemptionController/exemptionController.ts
  Back-End/controllers/feedbackController/feedbackController.ts
  Back-End/controllers/redisClient.ts
  Back-End/controllers/requisiteController/requisiteController.ts
  Back-End/controllers/timelineController/timelineController.ts
  Back-End/controllers/userDataController/userDataController.ts
  Back-End/index.ts
  Back-End/middleware/sentryMiddleware.ts
  Back-End/package.json
  front-end/.env
  front-end/.gitignore
  front-end/package.json
  front-end/src/pages/TimelinePage.js
Labels: bug

#161 Schedule generator
  front-end/package.json
  front-end/src/css/Navbar.css
  front-end/src/css/TimelinePage.css
  front-end/src/css/UserPage.css
  front-end/src/icons/download-icon.PNG
  front-end/src/pages/TimelinePage.js
Labels: User Story

#165 Backend Testing
  .gitignore
  Back-End/.DS_Store
  Back-End/controllers/courseController/courseController.ts
  Back-End/controllers/courseController/course_types.d.ts
  Back-End/package.json
  Back-End/routes/auth.ts
  Back-End/routes/coursepool.ts
  Back-End/routes/courses.ts
  Back-End/routes/exemption.ts
  Back-End/routes/timeline.ts
  Back-End/routes/userData.ts
  Back-End/tests/__mocks__/coursepool_mocks.js
  Back-End/tests/__mocks__/courses_mocks.js
  Back-End/tests/__mocks__/deficiency_mocks.js
  Back-End/tests/__mocks__/exemption_mocks.js
  Back-End/tests/__mocks__/timeline_mocks.js
  Back-End/tests/__mocks__/user_mocks.js
  Back-End/tests/coursepool.test.js
  Back-End/tests/courses.test.js
  Back-End/tests/deficiency.test.js
  Back-End/tests/exemption.test.js
  Back-End/tests/forgotpass.test.js
  Back-End/tests/login.test.js
  Back-End/tests/signup.test.js
  Back-End/tests/timeline.test.js
  Back-End/tests/userData.test.js
  front-end/.gitignore
  front-end/src/pages/TimelinePage.js
  init.sql
Labels: Testing

#166 Switched feedback button to redirect user to google form
  Back-End/coverage/.DS_Store
  Back-End/coverage/clover.xml
  Back-End/coverage/coverage-final.json
  Back-End/coverage/lcov-report/Util/DB_Ops.js.html
  Back-End/coverage/lcov-report/Util/HTTPCodes.js.html
  Back-End/coverage/lcov-report/Util/index.html
  Back-End/coverage/lcov-report/base.css
  Back-End/coverage/lcov-report/block-navigation.js
  Back-End/coverage/lcov-report/controllers/DBController/DBController.js.html
  Back-End/coverage/lcov-report/controllers/DBController/index.html
  Back-End/coverage/lcov-report/dist/Util/HTTPCodes.js.html
  Back-End/coverage/lcov-report/dist/Util/index.html
  Back-End/coverage/lcov-report/dist/routes/exemption.js.html
  Back-End/coverage/lcov-report/dist/routes/index.html
  Back-End/coverage/lcov-report/favicon.png
  Back-End/coverage/lcov-report/index.html
  Back-End/coverage/lcov-report/prettify.css
  Back-End/coverage/lcov-report/prettify.js
  Back-End/coverage/lcov-report/routes/auth.js.html
  Back-End/coverage/lcov-report/routes/coursepool.js.html
  Back-End/coverage/lcov-report/routes/courses.js.html
  Back-End/coverage/lcov-report/routes/deficiency.js.html
  Back-End/coverage/lcov-report/routes/exemption.js.html
  Back-End/coverage/lcov-report/routes/index.html
  Back-End/coverage/lcov-report/routes/timeline.js.html
  Back-End/coverage/lcov-report/routes/userData.js.html
  Back-End/coverage/lcov-report/sort-arrow-sprite.png
  Back-End/coverage/lcov-report/sorter.js
  Back-End/coverage/lcov-report/tests/exemption_mocks.js.html
  Back-End/coverage/lcov-report/tests/index.html
  Back-End/coverage/lcov.info
  front-end/src/components/Footer.js
Labels: enhancement

#169 fixd the credit calculation in the semester display
  front-end/src/pages/TimelinePage.js
Labels: bug
